### ISSUE TITLE
some questions thanks.

### ISSUE THREAD

**Issue by ruangf** [MartinKral/Slash-The-Hordes#35]
After reaching 1000 levels, the game will gradually become stuck

**Comment by MartinKral** [comment]
Checking the settings file, it seems that there are no more spawns after 1300 seconds:
Added endless spawners (you can add your own by setting the `stopDelay` to `-1`)

**Comment by ruangf** [comment]
Thank you for your answer. I tried to learn your project and learned a lot of knowledge. After I modified it, I added it to the wechat mini game. On IOS, the frame will be relatively dropped. After 1000 seconds~ I am trying to modify it, thank you very muc

**Comment by MartinKral** [comment]
It is possible that the device is running out of allocated memory, you can try to dispose of the objects which are no longer needed. (every enemy is part of an object pool and does not get disposed - just deactivated in order to be reused again)
