### ISSUE TITLE
Levelup UI has warning, please help

### ISSUE THREAD

**Issue by RonTang** [MartinKral/Slash-The-Hordes#39]
![image](https://github.com/MartinKral/Slash-The-Hordes/assets/4351322/1fb103e2-a83a-46af-8fbd-ba1487f358d4)
Thanks for sharing this project. I've learned a lot!!!

**Comment by MartinKral** [comment]
Should be fixed here:
https://github.com/MartinKral/Slash-The-Hordes/commit/1216d1afcbcb1d2773fbbec38120ada13341682c

There is one more bug with the animations in the newest version - the chest is missing the icon of the skill. Unfortunately I was unable to fix it for now - the solution would be to recreate the animation from scratch.
